---
- hosts: all
  remote_user: douglas
  become: yes
  tasks:
    - name: update packages
      dnf:
        name: "*"
        state: latest
      register: update_status

    - name: reboot when updated
      reboot:
      when: update_status.changed
